name: Deploy JS/CSS to Bunny CDN

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Upload assets to Bunny.net
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Upload your built files to Bunny Storage
      - name: Upload to Bunny Storage
        run: |
          curl -T dist/global.v1.js "https://storage.bunnycdn.com/${{ secrets.BUNNY_STORAGE_NAME }}/scripts/global.v1.js" -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}"
          curl -T dist/styles.v1.css "https://storage.bunnycdn.com/${{ secrets.BUNNY_STORAGE_NAME }}/styles/styles.v1.css" -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}"

      # Step 4: Purge the Bunny CDN cache (optional but recommended)
      - name: Purge Bunny CDN Cache
        run: |
          curl -X POST "https://api.bunny.net/purge?url=https://cdn.yourdomain.com/scripts/global.v1.js" -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}"
          curl -X POST "https://api.bunny.net/purge?url=https://cdn.yourdomain.com/styles/styles.v1.css" -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}"
